theme: jekyll-theme-slate
title: HiCOPS
description: Accelerated large-scale peptide identification from mass spectrometry data through HPC database peptide search
incremental: false
markdown: kramdown
timezone: America/New_York
plugins:
  - jekyll-toc

page_excerpts: true

# Google Analytics
google_analytics: G-4VZD1LZZ87

# main hicops repository url
main_repository_url: https://github.com/pcdslab/gicops

# show_downloads: true
