theme: jekyll-theme-slate
title: HiCOPS
description: Accelerated large-scale peptide identification from mass spectrometry data through HPC database peptide search
incremental: false
markdown: kramdown
timezone: America/New_York
plugins:
  - jekyll-toc

# Google Analytics
google_analytics: UA-179832111-1

page_excerpts: true

# show_downloads: true
