theme: jekyll-theme-slate
title: HiCOPS
description: Computational framework for scalable acceleration of database peptide search on supercomputers
incremental: false
markdown: kramdown
timezone: America/New_York
plugins:
  - jekyll-toc

page_excerpts: true

# Google Analytics
google_analytics: UA-199714067-1

# main hicops repository url
main_repository_url: https://github.com/pcdslab/gicops

# show_downloads: true
